version: "1.0"
info:
  model: int-scaffold
packages:
- name: MJANenv7260752Project
  gitServerName: GitHubMANOJ
  gitUrl: https://github.com/manoj-jannu-IBM
  gitUsername: manoj-jannu-IBM
  gitBranch: main
